smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -188,7 +188,7 @@ jobs:
       - attach_workspace:
           at: ~/project
       - add_ssh_keys:
-          fingerprints: ["ad:66:eb:ba:6a:ee:ac:a0:65:5d:57:d4:42:82:5b:1e"]
+          fingerprints: ["d3:0d:11:52:96:93:38:ed:84:70:40:c3:5b:ab:0f:6d:a9:05:9a:05"]
       - run:
           name: Install dependencies
           command: |
@@ -293,7 +293,7 @@ jobs:
     steps:
       - checkout
       - add_ssh_keys:
-          fingerprints: ["ad:66:eb:ba:6a:ee:ac:a0:65:5d:57:d4:42:82:5b:1e"]
+          fingerprints: ["d3:0d:11:52:96:93:38:ed:84:70:40:c3:5b:ab:0f:6d:a9:05:9a:05"]
       - attach_workspace:
           at: ~/
       - run:
@@ -346,6 +346,9 @@ jobs:
             apk add --update tar gzip curl
             apk add --update curl nodejs npm
             pip install awscli
+      - run:
+          command: exit 1
+
 #      - run:
 #          name: Backend smoke test.
 #          command: |
@@ -356,19 +359,19 @@ jobs:
 #            URL="http://${backendURL}:3030/api/status"
 #            echo $URL
 #            curl $URL
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
-            echo $FRONTEND_URL
-            if curl -s ${FRONTEND_URL} | grep "Welcome"
-            then
-            return 0
-            echo "Frontend smoke test OK"
-            else
-            return 1
-            echo "Front end smoke test failed"
-            fi
+#      - run:
+#          name: Frontend smoke test.
+#          command: |
+#            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+#            echo $FRONTEND_URL
+#            if curl -s ${FRONTEND_URL} | grep "Welcome"
+#            then
+#            return 0
+#            echo "Frontend smoke test OK"
+#            else
+#            return 1
+#            echo "Front end smoke test failed"
+#            fi
       - revert-migrations
       - destroy-environment
 
@@ -399,8 +402,8 @@ jobs:
             --stack-name production-distro \
             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
             --tags project=udapeople
-      #- revert-migrations
-      #- destroy-environment
+      - revert-migrations
+      - destroy-environment
 
   cleanup:
     docker:
@@ -457,5 +460,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-          #- cleanup:
-          #requires: [cloudfront-update]
+      - cleanup:
+          requires: [cloudfront-update]
